name: Consume composite

on:
  push:
  workflow_dispatch:

jobs:
  composite_consumer:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: lfraile-dotnet-2022-workshop/composite-action@main
        with:
          who-to-greet: 'DotNet 2022'
